#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'capstone-pkg','console_scripts','lidar_data'
__requires__ = 'capstone-pkg'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('capstone-pkg', 'console_scripts', 'lidar_data')()
    )
